import AdminNavbar from "@/components/admin/navbar";
import AdminSideBar from "@/components/admin/sideBav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <AdminNavbar />
      <div className="flex gap-12">
        <div>
          <AdminSideBar />
        </div>
        <div>
          {children}
        </div>
      </div>
    </div>
  );
}
